variable "instance_type" {}
variable "public_subnet_id" {}
variable "app_subnet_id" {}
variable "db_subnet_id" {}
variable "private_sg" {}
variable "public_sg" {}
variable "wordpress_db_sg" {}
variable "app_server_ip" {}
variable "app_server_dns" {}
variable "inbound_ips" {}
variable "onprem_dns_ips" {}
variable "onprem_dns_interface_ids" {}
variable "rds_db_name" {}
variable "rds_db_user" {}
variable "rds_db_password" {}
variable "ec2_ssm_instance_profile" {}
variable "windows_ami_id" {}
variable "ssh_key_name" {}
variable "db_endpoint" {}
variable "aws_dns_name" {}
variable "onprem_dns_name" {}
variable "onprem_vpc_cidr" {}