variable "aws_vpc_id" {}
variable "appserver_ip" {}
variable "private_sg" {}
variable "aws-app-1a" {}
variable "aws-app-1b" {}
variable "onprem_dns_ips" {}
variable "wordpress_db_address" {}
variable "aws_dns_name" {}
variable "onprem_dns_name" {}
variable "aws_db_dns_name" {}
variable "aws_app_dns_name" {}